# Generated by Django 5.1.7 on 2025-04-04 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_climb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climb',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='mountain',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='climb',
            name='date',
            field=models.DateField(verbose_name='Date Climbed'),
        ),
    ]
